### ISSUE TITLE
README usage example is not functional

### ISSUE THREAD

**Issue by jonnyjon** [Robophil/Product-Tour#10]
- the readme usage example appears out of date

**Comment by robophil** [comment]
Hi @jonnyjon,
For the example in *index.html* to work you need to run bower install.

I do have plans later for the project. Needs some improvements and more. I'll work on it later this month.
See [here](https://github.com/Robophil/Product-Tour/wiki/Roadmap)

**Comment by robophil** [comment]
If the issue is still there @jonnyjon, could you send a **PR** to fix this?

**Comment by jonnyjon** [comment]
Great, thank you.
