### ISSUE TITLE
Global styles causing side effects in my own styles

### ISSUE THREAD

**Issue by arojunior** [Robophil/Product-Tour#16]
https://github.com/robophil/Product-Tour/blob/4d20ea0c6b20f8c2702dd763f408f0d0f1b8c2e3/css/product-tour.css#L6-L24

Can we move these styles to another scope?
I spent more than an hour trying to do this, but I'm very bad with CSS.

The problem is that these styles are breaking my own styles.

**Comment by robophil** [comment]
Sure, send a PR
I actually am working on an improvement of the entire library, it’s been a while since I touched this.
