### ISSUE TITLE
Bad positioning

### ISSUE THREAD

**Issue by adrianratajczak** [Robophil/Product-Tour#2]
Hi, 
on every element I've got bad position of orange indicator. 18 px from bottom of element. 
Any idea why?
I am using provided css and js without modifications

**Comment by robophil** [comment]
Hi @adrianratajczak ,

Thanks for the feedback. This was done to avoid overlaying the target content directly. I'll push an update that allows you tweak the position of the orange indicator if need be for top, bottom, right or left.

**Comment by robophil** [comment]
Fixed
