### ISSUE TITLE
(refactor) Eliminating jQuery Dependency

### ISSUE THREAD

**Issue by 0duaht** [Robophil/Product-Tour#4]
Really nice tool. Leaving out the jQuery dependency would be cool. Looked through codebase. Could be refactored to use plain VanillaJS.

**Comment by robophil** [comment]
Sure. Would add that to the milestone for coming release. You could do this and send a PR? Contributors are also needed @andela-toduah

**Comment by 0duaht** [comment]
Namaste! @Robophil
