### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by DanielZambranoC** [Robophil/Product-Tour#9]
productTour.addNewTourSteps([element: '#sidebar-left', title: 'sadasd', content: 'asdasdasd', image: '', class: 'right']);

**Comment by robophil** [comment]
Sorry, @DanielZambranoC. `addNewTourSteps ` takes an array of objects. so it should be
``` javascript
     productTour.addNewTourSteps([
       {element: '#sidebar-left', title: 'sadasd', content: 'asdasdasd', image: '', class: 'right'}
     ]);
```
I've updated the **readme** file to show this. Thanks
